using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Content.Shared._Eclipse.Delusions;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Eclipse.Delusions;

[GenerateTypedNameReferences]
public sealed partial class DelusionDisplay : Control
{
    public DelusionDisplay(Delusion delusion)
    {
        RobustXamlLoader.Load(this);

        DelusionNameLabel.SetMarkup(delusion.GetLocName());
        DelusionDescLabel.SetMarkup(delusion.GetLocDesc());
    }
}
