using Content.Client.UserInterface.Controls;
using Content.Shared._Eclipse.Delusions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Eclipse.Delusions;

[GenerateTypedNameReferences]
public sealed partial class DelusionsMenu : FancyWindow
{
    public DelusionsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(DelusionsComponent comp, DelusionsBuiState state)
    {
        DelusionDisplayContainer.Children.Clear();

        foreach (var delusion in state.Delusions)
        {
            DelusionDisplayContainer.AddChild(new DelusionDisplay(delusion));
        }
    }
}
