using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._Eclipse.Delusions;
using Robust.Shared.Utility;

namespace Content.Client._Eclipse.Delusions.Eui;

[GenerateTypedNameReferences]
public sealed partial class DelusionContainer : BoxContainer
{
    public event Action? OnDelete;

    public DelusionContainer(Delusion? delusion = null)
    {
        RobustXamlLoader.Load(this);

        if (delusion != null)
        {
            DelusionTitle.Text = delusion.GetLocName();
            DelusionContent.TextRope = new Rope.Leaf(delusion.GetLocDesc());
        }

        Delete.OnPressed += _ => OnDelete?.Invoke();
    }

    public string Title => DelusionTitle.Text;
    public string Text => Rope.Collapse(DelusionContent.TextRope).Trim();
}
